// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['wails']['AppHandler']['GetAppInfo']();
}

export function Startup(arg1) {
  return window['go']['wails']['AppHandler']['Startup'](arg1);
}
