// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecovery(arg1) {
  return window['go']['wails']['AppHandler']['ClearRecovery'](arg1);
}

export function ConsumeUpdateNotice() {
  return window['go']['wails']['AppHandler']['ConsumeUpdateNotice']();
}

export function ExportDiagnostics() {
  return window['go']['wails']['AppHandler']['ExportDiagnostics']();
}

export function GetAppInfo() {
  return window['go']['wails']['AppHandler']['GetAppInfo']();
}

export function GetPreferences() {
  return window['go']['wails']['AppHandler']['GetPreferences']();
}

export function LoadRecovery(arg1) {
  return window['go']['wails']['AppHandler']['LoadRecovery'](arg1);
}

export function RecordUpdateCheck() {
  return window['go']['wails']['AppHandler']['RecordUpdateCheck']();
}

export function SavePreferences(arg1) {
  return window['go']['wails']['AppHandler']['SavePreferences'](arg1);
}

export function SaveRecovery(arg1, arg2) {
  return window['go']['wails']['AppHandler']['SaveRecovery'](arg1, arg2);
}

export function SetAutomaticUpdates(arg1) {
  return window['go']['wails']['AppHandler']['SetAutomaticUpdates'](arg1);
}

export function SetDensity(arg1) {
  return window['go']['wails']['AppHandler']['SetDensity'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['wails']['AppHandler']['SetTheme'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['AppHandler']['Startup'](arg1);
}
