// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {config} from '../models';
import {recovery} from '../models';
import {context} from '../models';

export function ClearRecovery(arg1:string):Promise<void>;

export function ConsumeUpdateNotice():Promise<string>;

export function ExportDiagnostics():Promise<string>;

export function GetAppInfo():Promise<wails.AppInfo>;

export function GetPreferences():Promise<config.Preferences>;

export function LoadRecovery(arg1:string):Promise<recovery.Checkpoint>;

export function RecordUpdateCheck():Promise<void>;

export function SavePreferences(arg1:config.Preferences):Promise<void>;

export function SaveRecovery(arg1:string,arg2:string):Promise<void>;

export function SetAutomaticUpdates(arg1:boolean):Promise<void>;

export function SetDensity(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
