// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {context} from '../models';

export function ChooseAutoBackupDirectory():Promise<backup.AutoBackupSettings>;

export function CreateBackup():Promise<backup.BackupInfo>;

export function DisableAutoBackup():Promise<void>;

export function ExportCustomers():Promise<backup.ExportResult>;

export function ExportQuotations():Promise<backup.ExportResult>;

export function GetAutoBackupSettings():Promise<backup.AutoBackupSettings>;

export function ImportCustomers(arg1:string,arg2:backup.ImportMapping):Promise<number>;

export function PreviewImport(arg1:string):Promise<backup.ImportPreview>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SelectImportFile():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function ValidateBackup():Promise<backup.ValidationResult>;
