// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup() {
  return window['go']['wails']['BackupHandler']['CreateBackup']();
}

export function ExportCustomers() {
  return window['go']['wails']['BackupHandler']['ExportCustomers']();
}

export function ExportQuotations() {
  return window['go']['wails']['BackupHandler']['ExportQuotations']();
}

export function ImportCustomers(arg1, arg2) {
  return window['go']['wails']['BackupHandler']['ImportCustomers'](arg1, arg2);
}

export function PreviewImport(arg1) {
  return window['go']['wails']['BackupHandler']['PreviewImport'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['wails']['BackupHandler']['RestoreBackup'](arg1);
}

export function SelectImportFile() {
  return window['go']['wails']['BackupHandler']['SelectImportFile']();
}

export function Startup(arg1) {
  return window['go']['wails']['BackupHandler']['Startup'](arg1);
}

export function ValidateBackup() {
  return window['go']['wails']['BackupHandler']['ValidateBackup']();
}
