// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {company} from '../models';
import {context} from '../models';

export function CompleteOnboarding(arg1:company.CompanyCreateDTO):Promise<void>;

export function CreateCompany(arg1:company.CompanyCreateDTO):Promise<company.CompanyDTO>;

export function GetActiveCompany():Promise<company.CompanyDTO>;

export function GetImageDataURI(arg1:string):Promise<string>;

export function IsFirstRun():Promise<boolean>;

export function SelectImage(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateCompany(arg1:company.CompanyUpdateDTO):Promise<company.CompanyDTO>;
