// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteOnboarding(arg1) {
  return window['go']['wails']['CompanyHandler']['CompleteOnboarding'](arg1);
}

export function CreateCompany(arg1) {
  return window['go']['wails']['CompanyHandler']['CreateCompany'](arg1);
}

export function GetActiveCompany() {
  return window['go']['wails']['CompanyHandler']['GetActiveCompany']();
}

export function GetImageDataURI(arg1) {
  return window['go']['wails']['CompanyHandler']['GetImageDataURI'](arg1);
}

export function IsFirstRun() {
  return window['go']['wails']['CompanyHandler']['IsFirstRun']();
}

export function SelectImage(arg1) {
  return window['go']['wails']['CompanyHandler']['SelectImage'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['CompanyHandler']['Startup'](arg1);
}

export function UpdateCompany(arg1) {
  return window['go']['wails']['CompanyHandler']['UpdateCompany'](arg1);
}
