// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['wails']['CustomerHandler']['CreateCustomer'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['wails']['CustomerHandler']['DeleteCustomer'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['wails']['CustomerHandler']['GetCustomer'](arg1);
}

export function ListCustomers(arg1) {
  return window['go']['wails']['CustomerHandler']['ListCustomers'](arg1);
}

export function SearchCustomers(arg1) {
  return window['go']['wails']['CustomerHandler']['SearchCustomers'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['CustomerHandler']['Startup'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['wails']['CustomerHandler']['UpdateCustomer'](arg1);
}
