// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {customer} from '../models';
import {context} from '../models';

export function CreateCustomer(arg1:customer.CustomerCreateDTO):Promise<customer.CustomerDTO>;

export function DeleteCustomer(arg1:string):Promise<void>;

export function GetCustomer(arg1:string):Promise<customer.CustomerDTO>;

export function ListCustomers(arg1:customer.CustomerListFilterDTO):Promise<customer.CustomerListDTO>;

export function SearchCustomers(arg1:string):Promise<Array<customer.CustomerDTO>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateCustomer(arg1:customer.CustomerUpdateDTO):Promise<customer.CustomerDTO>;
