// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {diagnostics} from '../models';
import {context} from '../models';

export function CaptureDiagnosticsProfile(arg1:string):Promise<string>;

export function ExportDiagnosticsRecording(arg1:string):Promise<string>;

export function GetDiagnosticsStatus():Promise<diagnostics.Status>;

export function OpenDiagnosticsFolder():Promise<void>;

export function RecordDiagnosticsOperation(arg1:string,arg2:number,arg3:string,arg4:Record<string, number>):Promise<void>;

export function RecordFrontendDiagnostics(arg1:string,arg2:number,arg3:Record<string, number>):Promise<void>;

export function StartDiagnosticsRecording(arg1:string):Promise<diagnostics.Status>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopDiagnosticsRecording():Promise<diagnostics.Status>;
