// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureDiagnosticsProfile(arg1) {
  return window['go']['wails']['DiagnosticsHandler']['CaptureDiagnosticsProfile'](arg1);
}

export function ExportDiagnosticsRecording(arg1) {
  return window['go']['wails']['DiagnosticsHandler']['ExportDiagnosticsRecording'](arg1);
}

export function GetDiagnosticsStatus() {
  return window['go']['wails']['DiagnosticsHandler']['GetDiagnosticsStatus']();
}

export function OpenDiagnosticsFolder() {
  return window['go']['wails']['DiagnosticsHandler']['OpenDiagnosticsFolder']();
}

export function RecordDiagnosticsOperation(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['DiagnosticsHandler']['RecordDiagnosticsOperation'](arg1, arg2, arg3, arg4);
}

export function RecordFrontendDiagnostics(arg1, arg2, arg3) {
  return window['go']['wails']['DiagnosticsHandler']['RecordFrontendDiagnostics'](arg1, arg2, arg3);
}

export function StartDiagnosticsRecording(arg1) {
  return window['go']['wails']['DiagnosticsHandler']['StartDiagnosticsRecording'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['DiagnosticsHandler']['Startup'](arg1);
}

export function StopDiagnosticsRecording() {
  return window['go']['wails']['DiagnosticsHandler']['StopDiagnosticsRecording']();
}
