// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GeneratePDF(arg1:string,arg2:string):Promise<string>;

export function GetDocumentLayoutDiagnostics(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetQuotationLayoutDiagnostics(arg1:string,arg2:string):Promise<any>;

export function GetQuotationPreviewPDF(arg1:string,arg2:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
