// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePDF(arg1, arg2) {
  return window['go']['wails']['DocumentHandler']['GeneratePDF'](arg1, arg2);
}

export function GetQuotationPreviewPDF(arg1, arg2) {
  return window['go']['wails']['DocumentHandler']['GetQuotationPreviewPDF'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['wails']['DocumentHandler']['Startup'](arg1);
}
