// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePDF(arg1, arg2) {
  return window['go']['wails']['DocumentHandler']['GeneratePDF'](arg1, arg2);
}

export function GetDocumentFonts() {
  return window['go']['wails']['DocumentHandler']['GetDocumentFonts']();
}

export function GetDocumentLayoutDiagnostics(arg1, arg2, arg3) {
  return window['go']['wails']['DocumentHandler']['GetDocumentLayoutDiagnostics'](arg1, arg2, arg3);
}

export function GetQuotationLayoutDiagnostics(arg1, arg2) {
  return window['go']['wails']['DocumentHandler']['GetQuotationLayoutDiagnostics'](arg1, arg2);
}

export function GetQuotationPreviewPDF(arg1, arg2) {
  return window['go']['wails']['DocumentHandler']['GetQuotationPreviewPDF'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['wails']['DocumentHandler']['Startup'](arg1);
}
