// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GenerateTempPDF(arg1:string,arg2:string):Promise<string>;

export function OpenPDF(arg1:string,arg2:string):Promise<void>;

export function PrintPDF(arg1:string,arg2:string):Promise<void>;

export function SaveDOCX(arg1:string,arg2:string):Promise<string>;

export function SavePDF(arg1:string,arg2:string):Promise<string>;

export function SharePDF(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
