// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateTempPDF(arg1, arg2) {
  return window['go']['wails']['ExportHandler']['GenerateTempPDF'](arg1, arg2);
}

export function OpenPDF(arg1, arg2) {
  return window['go']['wails']['ExportHandler']['OpenPDF'](arg1, arg2);
}

export function PrintPDF(arg1, arg2) {
  return window['go']['wails']['ExportHandler']['PrintPDF'](arg1, arg2);
}

export function SavePDF(arg1, arg2) {
  return window['go']['wails']['ExportHandler']['SavePDF'](arg1, arg2);
}

export function SharePDF(arg1, arg2) {
  return window['go']['wails']['ExportHandler']['SharePDF'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['wails']['ExportHandler']['Startup'](arg1);
}
