// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverLegacyData() {
  return window['go']['wails']['LegacyHandler']['DiscoverLegacyData']();
}

export function ImportLegacyData(arg1) {
  return window['go']['wails']['LegacyHandler']['ImportLegacyData'](arg1);
}

export function SkipLegacyData() {
  return window['go']['wails']['LegacyHandler']['SkipLegacyData']();
}

export function Startup(arg1) {
  return window['go']['wails']['LegacyHandler']['Startup'](arg1);
}
