// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {legacydata} from '../models';
import {context} from '../models';

export function DiscoverLegacyData():Promise<Array<legacydata.Candidate>>;

export function ImportLegacyData(arg1:string):Promise<void>;

export function SkipLegacyData():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
