// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {quotation} from '../models';
import {context} from '../models';

export function CreateQuotationDraft(arg1:quotation.QuotationCreateDTO):Promise<quotation.QuotationDTO>;

export function GetQuotation(arg1:string):Promise<quotation.QuotationDTO>;

export function SaveQuotationDocument(arg1:quotation.QuotationUpdateDocumentDTO):Promise<quotation.QuotationDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateQuotationCustomer(arg1:quotation.QuotationUpdateCustomerDTO):Promise<quotation.QuotationDTO>;
