// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {quotation} from '../models';
import {template} from '../models';
import {context} from '../models';

export function CreateQuotationDraft(arg1:quotation.QuotationCreateDTO):Promise<quotation.QuotationDTO>;

export function DeleteQuotation(arg1:string):Promise<void>;

export function DuplicateQuotation(arg1:string):Promise<quotation.QuotationDTO>;

export function FinalizeQuotation(arg1:string):Promise<quotation.QuotationDTO>;

export function GetQuotation(arg1:string):Promise<quotation.QuotationDTO>;

export function ListQuotations(arg1:quotation.QuotationListFilterDTO):Promise<quotation.QuotationListResponse>;

export function RecalculateQuotation(arg1:string):Promise<quotation.CalculationResultDTO>;

export function SaveAsTemplate(arg1:quotation.SaveAsTemplateDTO):Promise<template.TemplateDTO>;

export function SaveQuotationDocument(arg1:quotation.QuotationUpdateDocumentDTO):Promise<quotation.QuotationDTO>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateQuotationCustomer(arg1:quotation.QuotationUpdateCustomerDTO):Promise<quotation.QuotationDTO>;

export function UpdateQuotationStatus(arg1:string,arg2:string):Promise<quotation.QuotationDTO>;
