// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateQuotationDraft(arg1) {
  return window['go']['wails']['QuotationHandler']['CreateQuotationDraft'](arg1);
}

export function GetQuotation(arg1) {
  return window['go']['wails']['QuotationHandler']['GetQuotation'](arg1);
}

export function RecalculateQuotation(arg1) {
  return window['go']['wails']['QuotationHandler']['RecalculateQuotation'](arg1);
}

export function SaveQuotationDocument(arg1) {
  return window['go']['wails']['QuotationHandler']['SaveQuotationDocument'](arg1);
}

export function Startup(arg1) {
  return window['go']['wails']['QuotationHandler']['Startup'](arg1);
}

export function UpdateQuotationCustomer(arg1) {
  return window['go']['wails']['QuotationHandler']['UpdateQuotationCustomer'](arg1);
}
