// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneSectionDefinition(arg1) {
  return window['go']['wails']['SectionHandler']['CloneSectionDefinition'](arg1);
}

export function CreateSectionDefinition(arg1) {
  return window['go']['wails']['SectionHandler']['CreateSectionDefinition'](arg1);
}

export function DeleteSectionDefinition(arg1) {
  return window['go']['wails']['SectionHandler']['DeleteSectionDefinition'](arg1);
}

export function ListSectionDefinitions() {
  return window['go']['wails']['SectionHandler']['ListSectionDefinitions']();
}

export function Startup(arg1) {
  return window['go']['wails']['SectionHandler']['Startup'](arg1);
}

export function UpdateSectionDefinition(arg1) {
  return window['go']['wails']['SectionHandler']['UpdateSectionDefinition'](arg1);
}
