// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {section} from '../models';
import {context} from '../models';

export function CloneSectionDefinition(arg1:string):Promise<section.SectionDefinitionDTO>;

export function CreateSectionDefinition(arg1:section.SectionCreateDTO):Promise<section.SectionDefinitionDTO>;

export function DeleteSectionDefinition(arg1:string):Promise<void>;

export function ListSectionDefinitions():Promise<Array<section.SectionDefinitionDTO>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateSectionDefinition(arg1:section.SectionUpdateDTO):Promise<section.SectionDefinitionDTO>;
