// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTemplate(arg1) {
  return window['go']['wails']['TemplateHandler']['CreateTemplate'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['wails']['TemplateHandler']['DeleteTemplate'](arg1);
}

export function DuplicateTemplate(arg1) {
  return window['go']['wails']['TemplateHandler']['DuplicateTemplate'](arg1);
}

export function GetTemplate(arg1) {
  return window['go']['wails']['TemplateHandler']['GetTemplate'](arg1);
}

export function ListTemplates() {
  return window['go']['wails']['TemplateHandler']['ListTemplates']();
}

export function Startup(arg1) {
  return window['go']['wails']['TemplateHandler']['Startup'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['wails']['TemplateHandler']['UpdateTemplate'](arg1);
}
