// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {template} from '../models';
import {context} from '../models';

export function CreateTemplate(arg1:template.TemplateCreateDTO):Promise<template.TemplateDTO>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function DuplicateTemplate(arg1:string):Promise<template.TemplateDTO>;

export function GetTemplate(arg1:string):Promise<template.TemplateDTO>;

export function ListTemplates():Promise<Array<template.TemplateDTO>>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateTemplate(arg1:template.TemplateUpdateDTO):Promise<template.TemplateDTO>;
