// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelUpdateDownload() {
  return window['go']['wails']['UpdateHandler']['CancelUpdateDownload']();
}

export function CheckForUpdates() {
  return window['go']['wails']['UpdateHandler']['CheckForUpdates']();
}

export function DownloadUpdate() {
  return window['go']['wails']['UpdateHandler']['DownloadUpdate']();
}

export function InstallUpdate() {
  return window['go']['wails']['UpdateHandler']['InstallUpdate']();
}

export function SkipUpdateVersion() {
  return window['go']['wails']['UpdateHandler']['SkipUpdateVersion']();
}

export function Startup(arg1) {
  return window['go']['wails']['UpdateHandler']['Startup'](arg1);
}
