// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {context} from '../models';

export function CancelUpdateDownload():Promise<void>;

export function CheckForUpdates():Promise<update.CheckResult>;

export function DownloadUpdate():Promise<string>;

export function InstallUpdate():Promise<void>;

export function SkipUpdateVersion():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
