// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"go.uber.org/zap"
	"quotierlabs/backend/domain"
	"quotierlabs/backend/infrastructure/id"
	"quotierlabs/backend/infrastructure/logging"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	logger, err := logging.NewLogger()
	if err != nil {
		return nil, err
	}
	idGenerator := id.NewULIDGenerator()
	app := &App{
		Logger: logger,
		IDGen:  idGenerator,
	}
	return app, nil
}

// wire.go:

// InfrastructureSet provides all infrastructure dependencies
var InfrastructureSet = wire.NewSet(id.NewULIDGenerator, logging.NewLogger)

// App represents the DI composition root.
type App struct {
	Logger *zap.Logger
	IDGen  domain.IDGenerator
}
