// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"quotierlabs/backend/application/company"
	"quotierlabs/backend/application/customer"
	"quotierlabs/backend/application/onboarding"
	"quotierlabs/backend/application/section"
	"quotierlabs/backend/domain"
	"quotierlabs/backend/infrastructure/id"
	"quotierlabs/backend/infrastructure/logging"
	"quotierlabs/backend/infrastructure/sqlite"
	"quotierlabs/backend/transport/wails"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	logger, err := logging.NewLogger()
	if err != nil {
		return nil, err
	}
	idGenerator := id.NewULIDGenerator()
	db, err := ProvideDB()
	if err != nil {
		return nil, err
	}
	txManager := sqlite.NewGormTxManager(db)
	companyRepository := sqlite.NewCompanyRepository(db)
	customerRepository := sqlite.NewCustomerRepository(db)
	sectionDefinitionRepository := sqlite.NewSectionDefinitionRepository(db)
	templateRepository := sqlite.NewTemplateRepository(db)
	quotationRepository := sqlite.NewQuotationRepository(db)
	numberSequenceRepository := sqlite.NewNumberSequenceRepository(db)
	service := company.NewService(companyRepository, idGenerator)
	onboardingService := onboarding.NewService(service, txManager, sectionDefinitionRepository, templateRepository, numberSequenceRepository, idGenerator)
	companyHandler := wails.NewCompanyHandler(service, onboardingService)
	customerService := customer.NewService(customerRepository, idGenerator)
	customerHandler := wails.NewCustomerHandler(service, customerService)
	sectionService := section.NewService(sectionDefinitionRepository, idGenerator)
	sectionHandler := wails.NewSectionHandler(service, sectionService)
	app := &App{
		Logger:          logger,
		IDGenerator:     idGenerator,
		TxManager:       txManager,
		Companies:       companyRepository,
		Customers:       customerRepository,
		Sections:        sectionDefinitionRepository,
		Templates:       templateRepository,
		Quotations:      quotationRepository,
		Sequences:       numberSequenceRepository,
		CompanyService:  service,
		OnboardService:  onboardingService,
		CompanyHandler:  companyHandler,
		CustomerHandler: customerHandler,
		SectionHandler:  sectionHandler,
	}
	return app, nil
}

// wire.go:

func ProvideDB() (*gorm.DB, error) {
	return sqlite.NewDB("quotierlabs.db")
}

var InfrastructureSet = wire.NewSet(id.NewULIDGenerator, logging.NewLogger, ProvideDB, sqlite.NewGormTxManager, sqlite.NewCompanyRepository, sqlite.NewCustomerRepository, sqlite.NewSectionDefinitionRepository, sqlite.NewTemplateRepository, sqlite.NewQuotationRepository, sqlite.NewNumberSequenceRepository)

var ApplicationSet = wire.NewSet(company.NewService, onboarding.NewService, customer.NewService, section.NewService)

var TransportSet = wire.NewSet(wails.NewCompanyHandler, wails.NewCustomerHandler, wails.NewSectionHandler)

type App struct {
	Logger      *zap.Logger
	IDGenerator domain.IDGenerator
	TxManager   domain.TxManager
	Companies   domain.CompanyRepository
	Customers   domain.CustomerRepository
	Sections    domain.SectionDefinitionRepository
	Templates   domain.TemplateRepository
	Quotations  domain.QuotationRepository
	Sequences   domain.NumberSequenceRepository

	CompanyService  *company.Service
	OnboardService  *onboarding.Service
	CompanyHandler  *wails.CompanyHandler
	CustomerHandler *wails.CustomerHandler
	SectionHandler  *wails.SectionHandler
}
